### ISSUE TITLE
🐛 Designer Review - Add state text to the AU Map

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Website-v3#116] opened 2023-02-05 23:54 UTC
- [ ] Implement state names on the map

    ![Image](https://user-images.githubusercontent.com/25432120/216486476-1334ea4d-d274-48f5-a961-fddebf8f8b64.png)
**Figure: New site missing state text**

    ![Image](https://user-images.githubusercontent.com/25432120/216486533-5d5a6f8f-699c-4825-b1a8-51a4375bc924.png)
**Figure: Current site with state text**

**Comment by wicksipedia** [comment] 2023-02-06 03:00
this is a dupe of #109

**Closed by wicksipedia** 2023-02-06 03:00 UTC
